name: Opdater Frokost Kalender
on:
  schedule:
    - cron: '0 6 * * *' # Kører hver dag kl 06:00
  workflow_dispatch: # Gør det muligt at starte den manuelt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: node scrape.js
      - name: Commit og Push
        run: |
          git config --global user.name 'Robot'
          git config --global user.email 'robot@github.com'
          git add .
          git commit -m "Opdateret menu" || exit 0
          git push
